services:
  react-app_frontend:
    build: .
    container_name: react-staging-app
    ports:
      - "3000:80"
    restart: always
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=obum
      - CHOKIDAR_USEPOLLING=true